# Use the official Node.js image
FROM node:23

# Set the working directory in the container
WORKDIR /app/frontend

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Expose port 3000 for the React application
EXPOSE 3000

# Start the React application
CMD ["npm", "run", "dev"]
